import { notFound } from "next/navigation";
import Link from "next/link";
import { db } from "../../../lib/db";
import { env } from "../../../lib/env";

export default async function ProjectCaseStudy({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (!env.DATABASE_URL) notFound();
  const project = await db.project.findFirst({ where: { slug, published: true } });
  if (!project) notFound();

  return <main className="min-h-screen bg-[#f6f6f2] px-5 py-20 text-[#17211d] sm:px-8 lg:px-12"><article className="mx-auto max-w-5xl"><Link href="/#projects" className="text-sm font-bold text-[#657b00]">← Back to selected work</Link><header className="mt-16 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#657b00]">{project.category || "Case study"}</p><h1 className="mt-5 font-serif text-6xl leading-[.9] tracking-[-.06em] sm:text-8xl">{project.title}</h1><p className="mt-8 text-xl leading-8 text-[#52605a]">{project.shortDescription}</p>{(project.clientName || project.startDate || project.completionDate) && <p className="mt-5 text-sm font-bold text-[#52605a]">{project.clientName}{project.clientName && (project.startDate || project.completionDate) ? " · " : ""}{project.startDate?.toLocaleDateString("en-US", { month: "short", year: "numeric" })}{project.startDate && project.completionDate ? " - " : ""}{project.completionDate?.toLocaleDateString("en-US", { month: "short", year: "numeric" })}</p>}</header>{project.thumbnailUrl && <img src={project.thumbnailUrl} alt={project.title} className="mt-16 max-h-152 w-full rounded-3xl object-cover" />}</article><div className="mx-auto mt-20 grid max-w-5xl gap-12 md:grid-cols-3"><section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#657b00]">Problem</p><p className="mt-4 leading-7 text-[#52605a]">{project.challenges || project.fullDescription || project.shortDescription}</p></section><section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#657b00]">Solution</p><p className="mt-4 leading-7 text-[#52605a]">{project.solutions || "A focused product experience shaped around the project requirements."}</p></section><section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#657b00]">Result</p><p className="mt-4 leading-7 text-[#52605a]">{project.results || "The published project is available to explore through the links below."}</p></section></div><div className="mx-auto mt-12 flex max-w-5xl flex-wrap gap-3">{project.technologies.map((technology) => <span key={technology} className="rounded-full border border-[#17211d]/15 px-4 py-2 text-xs font-bold">{technology}</span>)}{project.demoUrl && <a href={project.demoUrl} target="_blank" rel="noreferrer" className="rounded-full bg-[#17211d] px-4 py-2 text-xs font-bold text-white">Visit live demo</a>}{project.githubUrl && <a href={project.githubUrl} target="_blank" rel="noreferrer" className="rounded-full border border-[#17211d]/20 px-4 py-2 text-xs font-bold">View source</a>}{project.clientUrl && <a href={project.clientUrl} target="_blank" rel="noreferrer" className="rounded-full border border-[#17211d]/20 px-4 py-2 text-xs font-bold">Visit client</a>}</div></main>;
}