"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check, Code2, ExternalLink, Github, Layers3, Mail, MapPin } from "lucide-react";
import { useState } from "react";
import Certifications from "./Certifications";
import type { AboutContent, Certification, Education, Experience, HeroContent, Profile, Project, Role, Service, SiteSettingsContent, Skill, SocialLink, Testimonial } from "../../types/portfolio";

type Props = { profile: Profile; hero: HeroContent | null; projects: Project[]; skills: Skill[]; testimonials: Testimonial[]; certifications: Certification[]; about: AboutContent | null; roles: Role[]; experience: Experience[]; education: Education[]; services: Service[]; socialLinks: SocialLink[]; siteSettings: SiteSettingsContent | null };

export default function PremiumPortfolio({ profile, hero, projects, skills, testimonials, certifications, about, roles, experience, education, services, socialLinks, siteSettings }: Props) {
  const fallbackRoles: Role[] = [
    { id: "engineering", title: profile.title || "Full-stack engineering", slug: "engineering", summary: "I turn complex requirements into dependable web applications, from database design to the final interface.", responsibilities: ["Architecture that stays maintainable", "Secure auth, APIs, and data flows", "Performance-minded frontend delivery"], technologies: [], achievements: [], skills: [], project_ids: [], cta_label: "Discuss engineering", cta_url: "#contact" },
    { id: "product", title: "Product-minded delivery", slug: "product-delivery", summary: "I help teams move from a rough idea to a clear, useful product with an interface that earns trust.", responsibilities: ["Clear product thinking before code", "Responsive, accessible experiences", "Fast feedback and visible progress"], technologies: [], achievements: [], skills: [], project_ids: [], cta_label: "Discuss a product", cta_url: "#contact" },
  ];
  const roleData = roles.length ? roles : fallbackRoles;
  const [roleIndex, setRoleIndex] = useState(0);
  const activeRole = roleData[roleIndex] || roleData[0];
  const aboutPoints = about?.highlights.length ? about.highlights : ["From idea to deployment", "Interfaces people understand", "Reliable APIs and data models", "Long-term ownership and iteration"];

  return (
    <div className="overflow-hidden bg-[#f6f6f2] text-[#17211d] selection:bg-[#e6ff65] selection:text-[#17211d]">
      <section id="hero" className="relative border-b border-[#17211d]/10">
        <div className="portfolio-grid absolute inset-0 opacity-40" />
        <div className="relative mx-auto max-w-7xl px-5 pb-20 pt-16 sm:px-8 lg:px-12 lg:pb-28 lg:pt-24">
          <div className="flex items-center justify-between text-xs font-bold uppercase tracking-[0.2em] text-[#52605a]"><span>Independent developer / Bangladesh</span><span className="hidden sm:block">Portfolio 2026</span></div>
          <div className="mt-16 grid items-end gap-12 lg:grid-cols-[1.15fr_.85fr] lg:gap-20">
            <div>
              <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#17211d]/15 bg-white/60 px-3 py-2 text-xs font-bold uppercase tracking-[0.16em]"><span className="h-2 w-2 rounded-full bg-[#b6d900] shadow-[0_0_0_5px_rgba(182,217,0,.18)]" />{hero?.availability_badge || profile.availability_status || "Available for new work"}</div>
              <h1 className="max-w-4xl font-serif text-[clamp(3.4rem,8vw,8.6rem)] leading-[.86] tracking-[-.07em]">{hero?.heading || "I build useful digital products."}</h1>
              <p className="mt-9 max-w-xl text-lg leading-8 text-[#52605a]">{hero?.description || profile.short_bio || "I design and develop modern web experiences that combine clean UX, reliable architecture, and measurable business value."}</p>
              <div className="mt-9 flex flex-wrap gap-3"><a href={hero?.primary_cta_url || "#contact"} className="inline-flex items-center gap-3 rounded-full bg-[#17211d] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#657b00]">{hero?.primary_cta_label || "Hire me"} <ArrowUpRight size={16} /></a><a href={hero?.secondary_cta_url || "#projects"} className="inline-flex items-center gap-3 rounded-full border border-[#17211d]/20 bg-white/40 px-6 py-3.5 text-sm font-bold transition hover:border-[#17211d]">{hero?.secondary_cta_label || "View my work"} <ArrowDownRight size={16} /></a>{profile.resume_url && <a href={profile.resume_url} download className="inline-flex items-center gap-2 px-3 py-3.5 text-sm font-bold text-[#52605a] underline decoration-[#b6d900] decoration-2 underline-offset-4">Download CV</a>}</div>
            </div>
            <div className="relative mx-auto w-full max-w-md lg:ml-auto"><div className="absolute -right-5 -top-5 z-10 grid h-24 w-24 rotate-6 place-items-center rounded-2xl bg-[#e6ff65] p-3 text-center text-xs font-bold uppercase leading-4 shadow-xl">Open to<br />good work</div><div className="aspect-[.86] overflow-hidden rounded-4xl bg-[#d9dfd5] shadow-[18px_18px_0_#dfe7b8]"><img src={hero?.image_url || profile.profile_image_url || "https://i.ibb.co.com/gMxQc4vH/profile.jpg"} alt={profile.name} className="h-full w-full object-cover grayscale-[.18] transition duration-700 hover:scale-105 hover:grayscale-0" /></div><div className="mt-4 flex items-center justify-between text-xs font-bold uppercase tracking-[.16em] text-[#52605a]"><span>{profile.name}</span><span>{profile.title}</span></div></div>
          </div>
          <div className="mt-16 flex items-center gap-3 text-xs font-bold uppercase tracking-[.2em] text-[#52605a]"><span className="h-px w-10 bg-[#b6d900]" />Scroll to explore</div>
        </div>
      </section>

      <section id="about" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><div><p className="eyebrow">01 / {about?.title || "How I work"}</p><h2 className="section-title mt-5">Technology is only useful when it solves the right problem.</h2></div><div><p className="max-w-2xl text-xl leading-9 text-[#52605a]">{about?.description || profile.long_bio || "I care about the parts of product development that make a difference: a clear interface, a solid foundation, and the discipline to ship thoughtfully."}</p><div className="mt-10 grid gap-3 sm:grid-cols-2">{aboutPoints.map((point, index) => <div key={point} className="flex gap-3 border-t border-[#17211d]/15 py-4 text-sm font-bold"><span className="text-[#91aa00]">0{index + 1}</span>{point}</div>)}</div></div></div></section>

      <section id="roles" className="border-y border-[#17211d]/10 bg-[#e9eee4]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">02 / Role lens</p><h2 className="section-title mt-5 max-w-2xl">The same craft, tuned to the work in front of us.</h2></div><div className="flex flex-wrap rounded-full border border-[#17211d]/15 bg-white/60 p-1" role="tablist" aria-label="Role perspective">{roleData.map((role, index) => <button key={role.id} onClick={() => setRoleIndex(index)} className={`rounded-full px-4 py-2 text-xs font-bold uppercase tracking-[.12em] transition ${roleIndex === index ? "bg-[#17211d] text-white" : "text-[#52605a]"}`} role="tab" aria-selected={roleIndex === index}>{role.title}</button>)}</div></div><AnimatePresence mode="wait"><motion.div key={activeRole.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} transition={{ duration: .25 }} className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-2xl font-serif italic text-[#657b00]">{activeRole.title}</p><p className="mt-5 max-w-md text-lg leading-8 text-[#52605a]">{activeRole.summary}</p><a href={activeRole.cta_url || "#contact"} className="mt-7 inline-flex items-center gap-2 text-sm font-bold underline decoration-[#b6d900] decoration-2 underline-offset-4">{activeRole.cta_label || "Let&apos;s talk"} <ArrowUpRight size={15} /></a></div><div className="grid gap-3 sm:grid-cols-3">{activeRole.responsibilities.map((point) => <div key={point} className="min-h-40 rounded-2xl border border-[#17211d]/10 bg-white/60 p-5"><Check className="mb-8 text-[#91aa00]" size={19} /><p className="text-sm font-bold leading-6">{point}</p></div>)}</div></motion.div></AnimatePresence></div></section>

      <section id="projects" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mb-12 flex items-end justify-between gap-6"><div><p className="eyebrow">03 / Selected work</p><h2 className="section-title mt-5">Built for the real world.</h2></div><span className="hidden text-sm text-[#52605a] sm:block">{projects.length} published {projects.length === 1 ? "project" : "projects"}</span></div><div className="grid gap-6 md:grid-cols-2">{projects.map((project, index) => <article key={project.id} className={`group overflow-hidden rounded-3xl border border-[#17211d]/10 bg-white ${index === 0 ? "md:col-span-2" : ""}`}><div className={`grid ${index === 0 ? "lg:grid-cols-[1.15fr_.85fr]" : ""}`}><div className={`relative min-h-64 overflow-hidden bg-[#dce3d7] ${index === 0 ? "lg:min-h-120" : ""}`}>{project.thumbnail_url ? <img src={project.thumbnail_url} alt={project.title} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /> : <div className="grid h-full place-items-center"><Layers3 size={54} className="text-[#8c9a86]" /></div>}<div className="absolute left-5 top-5 rounded-full bg-[#f6f6f2]/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em]">{project.category || "Web product"}</div></div><div className="flex flex-col justify-between p-6 sm:p-8"><div><div className="mb-10 flex items-center justify-between text-xs font-bold text-[#91aa00]"><span>0{index + 1}</span><span>Case study</span></div><a href={`/projects/${project.slug}`} className="group/title"><h3 className="text-3xl font-serif leading-tight group-hover/title:text-[#657b00]">{project.title}</h3></a><p className="mt-4 leading-7 text-[#52605a]">{project.short_description}</p></div><div className="mt-10"><div className="mb-5 flex flex-wrap gap-2">{project.technologies.slice(0, 5).map((tech) => <span key={tech} className="rounded-full bg-[#edf1e7] px-3 py-1 text-[11px] font-bold text-[#52605a]">{tech}</span>)}</div><div className="flex flex-wrap gap-4 text-sm font-bold"><a href={`/projects/${project.slug}`} className="inline-flex items-center gap-2 underline decoration-[#b6d900] decoration-2 underline-offset-4">Read case study <ArrowUpRight size={14} /></a>{project.demo_url && <a href={project.demo_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-[#52605a]">Live demo <ExternalLink size={14} /></a>}{project.github_url && <a href={project.github_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-[#52605a]"><Github size={15} /> Source</a>}</div></div></div></div></article>)}</div></section>

      {services.length > 0 && <section id="services" className="border-y border-[#17211d]/10 bg-[#e9eee4]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><p className="eyebrow">04 / Services</p><h2 className="section-title mt-5 max-w-3xl">Useful work for teams moving forward.</h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <article key={service.id} className="rounded-2xl border border-[#17211d]/10 bg-white/60 p-6"><p className="text-sm font-bold text-[#91aa00]">0{index + 1}</p><h3 className="mt-8 text-2xl font-serif">{service.title}</h3><p className="mt-3 leading-7 text-[#52605a]">{service.short_description}</p>{service.features.length > 0 && <ul className="mt-6 space-y-2 text-sm text-[#52605a]">{service.features.map((feature) => <li key={feature} className="flex gap-2"><Check size={15} className="mt-0.5 shrink-0 text-[#91aa00]" />{feature}</li>)}</ul>}</article>)}</div></div></section>}

      {experience.length > 0 && <section id="experience" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">05 / Experience</p><h2 className="section-title mt-5">Work that compounds.</h2></div><div className="space-y-8">{experience.map((item) => <article key={item.id} className="border-t border-[#17211d]/15 pt-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-2xl font-serif">{item.position}</h3><span className="text-xs font-bold uppercase tracking-[.12em] text-[#657b00]">{item.company}</span></div><p className="mt-3 text-sm text-[#52605a]">{item.start_date ? new Date(item.start_date).toLocaleDateString("en-US", { month: "short", year: "numeric" }) : ""} - {item.current_position ? "Present" : item.end_date ? new Date(item.end_date).toLocaleDateString("en-US", { month: "short", year: "numeric" }) : ""}{item.location ? ` · ${item.location}` : ""}</p><p className="mt-4 max-w-2xl leading-7 text-[#52605a]">{item.description}</p></article>)}</div></div></section>}

      {education.length > 0 && <section id="education" className="border-y border-[#17211d]/10 bg-[#e9eee4]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div className="grid gap-8 md:grid-cols-3"><div><p className="eyebrow">06 / Education</p><h2 className="mt-5 font-serif text-4xl">Foundations matter.</h2></div>{education.map((item) => <article key={item.id} className="border-t border-[#17211d]/15 pt-4"><h3 className="text-xl font-serif">{item.degree}</h3><p className="mt-2 text-sm font-bold">{item.institution}</p><p className="mt-1 text-sm text-[#52605a]">{item.field}{item.grade ? ` · ${item.grade}` : ""}</p></article>)}</div></div></section>}

      <section id="skills" className="bg-[#17211d] text-[#f6f6f2]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#b6d900]">07 / Working toolkit</p><h2 className="section-title mt-5 text-[#f6f6f2]">The tools behind the outcome.</h2><p className="mt-6 max-w-md leading-7 text-[#aab5ad]">A practical stack, chosen for the job. No badges for the sake of badges.</p></div><div className="grid grid-cols-2 gap-x-8 gap-y-8 sm:grid-cols-3">{skills.map((skill) => <div key={skill.id} className="border-t border-white/15 pt-4"><p className="text-sm font-bold">{skill.name}</p><p className="mt-2 text-xs uppercase tracking-[.14em] text-[#91aa00]">{skill.category}</p></div>)}</div></div></div></section>

      {certifications.length > 0 && <Certifications certifications={certifications} />}

      {testimonials.length > 0 && <section id="proof" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">05 / Proof of work</p><h2 className="section-title mt-5">Good work leaves a trace.</h2></div><div className="space-y-6">{testimonials.slice(0, 2).map((item) => <blockquote key={item.id} className="border-l-2 border-[#b6d900] pl-6 text-xl leading-8">“{item.comment}”<footer className="mt-4 text-xs font-bold uppercase tracking-[.14em] text-[#52605a]">{item.name}{item.company ? ` / ${item.company}` : ""}</footer></blockquote>)}</div></div></section>}

      <section className="bg-[#e6ff65]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 px-5 py-20 sm:px-8 lg:flex-row lg:items-end lg:px-12 lg:py-28"><div><p className="eyebrow">06 / Start a conversation</p><h2 className="mt-5 max-w-3xl font-serif text-5xl leading-[.95] tracking-tighter sm:text-7xl">Have a product idea?<br /><em>Let&apos;s build it.</em></h2></div><a href="#contact" className="inline-flex w-fit items-center gap-3 rounded-full bg-[#17211d] px-6 py-4 text-sm font-bold text-white transition hover:bg-[#657b00]">Let&apos;s discuss your project <ArrowUpRight size={17} /></a></div></section>
      <div className="mx-auto flex max-w-7xl flex-wrap items-center gap-5 px-5 py-8 text-sm text-[#52605a] sm:px-8 lg:px-12"><span className="inline-flex items-center gap-2"><MapPin size={15} />{profile.location || "Available remotely"}</span>{profile.email && <a href={`mailto:${profile.email}`} className="inline-flex items-center gap-2 hover:text-[#657b00]"><Mail size={15} />{profile.email}</a>}{socialLinks.map((link) => <a key={link.id} href={link.url} target="_blank" rel="noreferrer" className="hover:text-[#657b00]">{link.label || link.platform}</a>)}<span className="ml-auto inline-flex items-center gap-2"><Code2 size={15} />{siteSettings?.professional_title || profile.title}</span><span className="w-full border-t border-[#17211d]/10 pt-5">{siteSettings?.footer_text || siteSettings?.copyright_text || `© ${new Date().getFullYear()} ${siteSettings?.site_name || profile.name}`}</span></div>
    </div>
  );
}